name: StopReason
version: 1.0.0
author: mk499490
main: Main
website: https://github.com/mk499490/stopreason
commands:
  stop:
    description: Stop the server with reason.
    usage: /stop [reason]
  restart:
    description: Restart the server with reason.
    usage: /restart [reason]